version: '3'
name: 'pcq2'

volumes:
  pcq2_sticker_database_data: {}
  pcq2_search_database_data: {}

services:
  sticker_service:
    build:
      context: ./StickerService/
      dockerfile: Dockerfile
    image: krazydocker/pcq2-sticker-service:latest
    container_name: pcq2_service_api
    platform: linux/x86_64
    depends_on:
      - sticker_db
    volumes:
      - ./StickerService:/code/app
    environment:
      - DB_HOST=${STICKER_DB_HOST}
      - DB_PORT=${STICKER_DB_PORT}
      - DB_NAME=${STICKER_DB_NAME}
      - DB_USER=${STICKER_DB_USER}
      - DB_PASSWORD=${STICKER_DB_PASSWORD}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - REDIS_HOST=${STICKER_REDIS_HOST}
      - REDIS_PORT=${STICKER_REDIS_PORT}
    ports:
      - "8000:8080"

  sticker_db:
    build:
      context: ./
      dockerfile: docker/database/Dockerfile
    image: krazydocker/pcq2-sticker-database:latest
    container_name: pcq2_sticker_database
    volumes:
      - pcq2_sticker_database_data:/var/lib/postgresql/data
    environment:
      - DB_NAME=${STICKER_DB_NAME}
      - DB_USER=${STICKER_DB_USER}
      - DB_PASSWORD=${STICKER_DB_PASSWORD}
      - POSTGRES_PASSWORD=${STICKER_POSTGRES_PASSWORD}
    restart: always
    ports:
      - "5432:${STICKER_DB_PORT}"

  sticker_cache:
    image: redis:6
    container_name: pcq2_sticker_cache

  search_service:
    build:
      context: ./SearchService/
      dockerfile: Dockerfile
    image: krazydocker/pcq2-search-service:latest
    container_name: pcq2_search_service
    platform: linux/x86_64
    depends_on:
      - search_db
    volumes:
      - ./SearchService:/code/app
    environment:
      - DB_HOST=${SEARCH_DB_HOST}
      - DB_PORT=${SEARCH_DB_PORT}
      - DB_NAME=${SEARCH_DB_NAME}
      - DB_USER=${SEARCH_DB_USER}
      - DB_PASSWORD=${SEARCH_DB_PASSWORD}
    ports:
      - "8118:8080"

  search_db:
    build:
      context: ./
      dockerfile: docker/database/Dockerfile
    image: krazydocker/pcq2-search-database:latest
    container_name: pcq2_search_database
    volumes:
      - pcq2_search_database_data:/var/lib/postgresql/data
    environment:
      - DB_NAME=${SEARCH_DB_NAME}
      - DB_USER=${SEARCH_DB_USER}
      - DB_PORT=${SEARCH_DB_PORT}
      - DB_PASSWORD=${SEARCH_DB_PASSWORD}
      - POSTGRES_PASSWORD=${SEARCH_POSTGRES_PASSWORD}
    restart: always
    ports:
      - "6432:${STICKER_DB_PORT}"
