# Generated by Django 4.2.1 on 2023-05-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagevector',
            name='image',
        ),
        migrations.AddField(
            model_name='imagevector',
            name='filename',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
