# Generated by Django 4.2.1 on 2023-05-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectors', '0002_remove_imagevector_image_imagevector_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagevector',
            old_name='vector',
            new_name='tensor_blob',
        ),
        migrations.AddField(
            model_name='imagevector',
            name='tensor_shape',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
