# Generated by Django 4.2.1 on 2023-05-18 17:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickerQuery',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=255, unique=True)),
                ('usage', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stickerfeedback',
            name='query',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='stickers.stickerquery'),
            preserve_default=False,
        ),
    ]
