# Generated by Django 4.2.1 on 2023-05-19 08:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0002_stickerquery_stickerfeedback_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickerQueryFeedback',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='query_feedback', to='stickers.stickerquery')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StickerQueryScore',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('positives', models.PositiveIntegerField(default=0)),
                ('negatives', models.PositiveIntegerField(default=0)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='query_scores', to='stickers.stickerquery')),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sticker_scores', to='stickers.sticker')),
            ],
            options={
                'unique_together': {('query', 'sticker')},
            },
        ),
        migrations.DeleteModel(
            name='StickerFeedback',
        ),
    ]
