# Generated by Django 4.2.1 on 2023-05-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0003_stickerqueryfeedback_stickerqueryscore_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StickerQueryFeedback',
        ),
    ]
